---
title: "RWorksheet#4"
author: "Carl Dave Labanero"
date: "2023-10-25"
output: pdf_document
---

``` {r num1A}
 ShoeSize <- c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,13.0,7.5,10.5,8,5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0)
Gender <- c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
  Height <- c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0)
dab <- data.frame(ShoeSize,Height,Gender)
dab
```
```{r num1B}
m_subset <-subset(dab, Gender == "M", select = c("ShoeSize", "Height"))
f_subset <-subset(dab,Gender == "F", select = c("ShoeSize", "Height"))


m_subset
f_subset
```
```{r num1C}

Shoesize <- mean(dab$ShoeSize)
height <- mean(dab$Height)
Shoesize
height
```
``` {r num1D}
#Although there is some association between shoe size and height, this 
#correlation is not exact because these two factors are not totally
#dependent on one another.
```
``` {r num2}
months_vector <- c("March","April","January","November","January",
                   "September","October","September","November","August",
                   "January","November","November","February","May","August",
                   "July","December","August","August","September","November",
                   "February","April")

factor_months_vector <- factor(months_vector)

factor_months_vector
```
```{r num3}

summary(months_vector)

summary(factor_months_vector)
```
```{r num4}

dadiarect_vector <- c("East", "West", "North")
dafreque_vector <- c(1, 4, 3)

new_order_data <- factor(factor_data, levels = c("East", "West", "North"))

print(new_order_data)
```
```{r num5}


