---
title: "RworkSheet#4B><"
author: "Carl Dave Labanero BSIT-2B"
date: "2023-11-24"
output: pdf_document
---

``` {r num1}

vectorA <- c(1, 2, 3, 4, 5)
matrixA <- matrix(0, nrow = 5, ncol = 5)

for (i in 1:5) {
  for (j in 1:5) {
    matrixA[i, j] <- abs(vectorA[i] - vectorA[j])
  }
}
matrixA
```

``` {r num2}
n <- 5  # The number of rows

for (i in 1:n) {
  for (j in 1:i) {
    cat("*")
  }
  cat("\n")
}
```

``` {r num3}

input_number <- as.numeric(readline("Enter a number to start the Fibonacci sequence: "))

assume_number <- 0
a <- 0
b <- 1

repeat {

  if (a > 500) {
    break
  }
  

  if (a >= assume_number) {
    cat(a, " ")
  }
  
  temp <- a + b
  a <- b
  b <- temp
}

cat("\n")

```

``` {r num4 A}
table <- read.table(file = 'shoesize.csv', header = TRUE, sep = ',')
table

```

``` {r  A}
head(table, n = 6)
```


``` {r num4 B}
male_subset <- subset(table, Gender == "M")
female_subset <- subset(table, Gender == "F")
male_count <- nrow(male_subset)
female_count <- nrow(female_subset)
cat("Number of Male observations:", male_count, "\n")
cat("Number of Female observations:", female_count, "\n")
#Number of Male observations: 14 
#Number of Female observations: 14 
```


``` {r  C}

data <- data.frame(
  Respondents = 1:10,
  Sex = c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male"),
  Fathers_Occupation = c(1, 2, 3, 3, 1, 2, 2, 3, 1, 3),
  Person_at_Home = c(5, 7, 3, 8, 6, 4, 4, 2, 11, 6),
  Siblings_at_school = c(2, 3, 0, 5, 2, 3, 1, 2, 6, 2),
  Types_of_houses = c("Wood", "Concrete", "Concrete", "Wood", "Semi-Concrete", "Semi-Concrete", "Wood", "Semi-Concrete", "Semi-Concrete", "Concrete")
)

gender_counts <- table(data$Sex)


bar_colors <- c("black", "gray")

barplot(gender_counts, main="Number of Males and Females", xlab="Sex", ylab="Count", col=bar_colors,
        legend.text=c("Male", "Female"), beside=TRUE)
legend("topright", legend=c("Male", "Female"), fill=bar_colors)

``` 

``` {r  num5}

expenses <- c(Food = 60, Electricity = 10, Savings = 5, Miscellaneous = 25)

pie(expenses, labels = paste(names(expenses), "(", round((expenses/sum(expenses))*100), "%)"), 
    col = c("black", "gray", "white", "green"),
    main = "Monthly Expenses of Dela Cruz Family")

legend("topright", legend = names(expenses), fill = c("black", "gray", "white", "green"))

```

``` {r  num6A}
data(iris)
str(iris)
```
``` {r  num6B}
mean_values <- c(mean(iris$Sepal.Length),
mean(iris$Sepal.Width),
mean(iris$Petal.Length),
mean(iris$Petal.Width))

```

``` {r  num6C}
pie(table(iris$Species), labels = c("Setosa", "Versicolor", "Virginica"), col = c("blue", "red", "yellow"), main = "Species Distribution")

```

```{r numD}
setosa_data <- iris[iris$Species == "setosa", ]
versicolor_data <- iris[iris$Species == "versicolor", ]
virginica_data <- iris[iris$Species == "virginica", ]

head(setosa_data, 6)
head(versicolor_data, 6)
head(virginica_data, 6)

```
```{r numE}
plot(x = iris$Sepal.Length[iris$Species == "setosa"], y = iris$Sepal.Width[iris$Species == "setosa"], pch = 16, col = "violet", main = "Iris Dataset", xlab = "Sepal Length", ylab = "Sepal Width")
points(x = iris$Sepal.Length[iris$Species == "versicolor"], y = iris$Sepal.Width[iris$Species == "versicolor"], pch = 17, col = "red")
points(x = iris$Sepal.Length[iris$Species == "virginica"], y = iris$Sepal.Width[iris$Species == "virginica"], pch = 18, col = "black")

```
```{r numF}
#The scatterplot shows that, in comparison to the versicolor and virginica  species, the setosa species has smaller measures for both sepal.length and sepal.width. While the values for sepal.length and sepal.width of the versicolor species are more than those of the setosa species, they are still less than those of the virginica species, which has the highest values of these two characteristics out of the three species.
```
``` {r num7}
#Can't Find RWorksheet 4B in Drive anymore thats why i cant finish my 4BB
```